#!/bin/sh
sxmo_setpineled red 0
sxmo_setpineled blue 0
sxmo_setpineled green 0
echo 750 > /sys/devices/platform/backlight/backlight/backlight/brightness #scale goes from 0-1000 on kernel 5.8
xrandr --dpi 192
xsetroot -mod 29 29 -fg '#0b3a4c' -bg '#082430'
if [ -f /usr/lib/X11/xdm/wallpaper.jpg ]; then
	feh --bg-fill -z /usr/lib/X11/xdm/wallpaper.jpg
fi
if [ -f /usr/lib/X11/xdm/welcome.ogg ]; then
	mpv --quiet --no-video /usr/lib/X11/xdm/welcome.ogg &
fi
if which svkbd-mobile-intl; then
	svkbd-mobile-intl &
elif which svkbd-mobile-plain; then
	svkbd-mobile-plain &
else
	svkbd-sxmo &
fi
